### ISSUE TITLE
Metadata not initialized

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Output-Biomass-By-Age#5]

**Comment by bmarron18** [comment]
Sure enough. The run of "scenario_s2e1.txt", which calls "Biomass Succession" + "Base Wind" + "Output Max Species Age" + "Output Biomass-by-Age", produces no subfolder for "Output Biomass by Age" in the folder "Metadata."  (The run correctly produces a Metadata subfolder "Output Max Species Age")

**Comment by bmarron18** [comment]
Issue can be closed
